<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ReasonsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $reasons = [
            ['id' => 1, 'title' => 'ACIDENTE DE TRABALHO', 'active' => true],
            ['id' => 2, 'title' => 'ACIDENTE DE TRÂNSITO CARRO/BICICLETA', 'active' => true],
            ['id' => 3, 'title' => 'ACIDENTE DE TRÂNSITO CARRO/CARRO', 'active' => true],
            ['id' => 4, 'title' => 'ACIDENTE DE TRÂNSITO CARRO/MOTO', 'active' => true],
            ['id' => 5, 'title' => 'ACIDENTE DE TRÂNSITO MOTO/BICICLETA', 'active' => true],
            ['id' => 6, 'title' => 'ACIDENTE DE TRÂNSITO MOTO/MOTO', 'active' => true],
            ['id' => 7, 'title' => 'ACIDENTE DE TRÂNSITO NÃO ESPECIFICADO', 'active' => true],
            ['id' => 8, 'title' => 'ACIDENTE DOMESTICO', 'active' => true],
            ['id' => 9, 'title' => 'AFOGAMENTO', 'active' => true],
            ['id' => 10, 'title' => 'AGRESSÃO DOMESTICA', 'active' => true],
            ['id' => 11, 'title' => 'AGRESSÃO FISICA', 'active' => true],
            ['id' => 12, 'title' => 'ALERGIA', 'active' => true],
            ['id' => 13, 'title' => 'ARDÊNCIA AO URINAR', 'active' => true],
            ['id' => 14, 'title' => 'ATROPELAMENTO', 'active' => true],
            ['id' => 15, 'title' => 'AVALIAÇAO C/ CIRURGIÃO', 'active' => true],
            ['id' => 16, 'title' => 'AVALIACÃO COM GENECOLOGISTA', 'active' => true],
            ['id' => 17, 'title' => 'AVALIAÇAO COM ORTOPETISTA', 'active' => true],
            ['id' => 18, 'title' => 'AVALIAÇÃO OBSTÉTRICA', 'active' => true],
            ['id' => 19, 'title' => 'AZIA', 'active' => true],
            ['id' => 20, 'title' => 'BAQUE', 'active' => true],
            ['id' => 21, 'title' => 'CANSAÇO', 'active' => true],
            ['id' => 22, 'title' => 'CÓLICA', 'active' => true],
            ['id' => 23, 'title' => 'CONSTIPAÇÃO', 'active' => true],
            ['id' => 24, 'title' => 'CONTRAÇÃO UTERINA', 'active' => true],
            ['id' => 25, 'title' => 'CONVULSÃO', 'active' => true],
            ['id' => 26, 'title' => 'CORPO ESTRANHO', 'active' => true],
            ['id' => 27, 'title' => 'CORPO ESTRANHO NA GARGANTA', 'active' => true],
            ['id' => 28, 'title' => 'CORPO ESTRANHO NO NARIZ', 'active' => true],
            ['id' => 29, 'title' => 'CORPO ESTRANHO NO OLHO', 'active' => true],
            ['id' => 30, 'title' => 'CORPO ESTRANHO NO OUVIDO', 'active' => true],
            ['id' => 31, 'title' => 'CORTE', 'active' => true],
            ['id' => 32, 'title' => 'CRISE DE ASMA', 'active' => true],
            ['id' => 33, 'title' => 'CURATIVO', 'active' => true],
            ['id' => 34, 'title' => 'DESMAIOS', 'active' => true],
            ['id' => 35, 'title' => 'DIARRÉIA', 'active' => true],
            ['id' => 36, 'title' => 'DOR ABDOMINAL', 'active' => true],
            ['id' => 37, 'title' => 'DOR AO URINAR', 'active' => true],
            ['id' => 38, 'title' => 'DOR DE BARRIGA/ESTÔMAGO', 'active' => true],
            ['id' => 39, 'title' => 'DOR DE CABEÇA', 'active' => true],
            ['id' => 40, 'title' => 'DOR DE DENTE', 'active' => true],
            ['id' => 41, 'title' => 'DOR DE GARGANTA', 'active' => true],
            ['id' => 42, 'title' => 'DOR DE OUVIDO', 'active' => true],
            ['id' => 43, 'title' => 'DOR EM MEMBROS INFERIORES', 'active' => true],
            ['id' => 44, 'title' => 'DOR EM MEMBROS SUPERIORES', 'active' => true],
            ['id' => 45, 'title' => 'DOR NA COLUNA', 'active' => true],
            ['id' => 46, 'title' => 'DOR NA FACE', 'active' => true],
            ['id' => 47, 'title' => 'DOR NA NUCA', 'active' => true],
            ['id' => 48, 'title' => 'DOR NA VIRILIA', 'active' => true],
            ['id' => 49, 'title' => 'DOR NÃO ESPECIFICADA', 'active' => true],
            ['id' => 50, 'title' => 'DOR NAS COSTAS', 'active' => true],
            ['id' => 51, 'title' => 'DOR NO CORPO', 'active' => true],
            ['id' => 52, 'title' => 'DOR NO PEITO', 'active' => true],
            ['id' => 53, 'title' => 'DOR NO PESCOÇO', 'active' => true],
            ['id' => 54, 'title' => 'DOR NOS OLHOS', 'active' => true],
            ['id' => 55, 'title' => 'DOR NOS OSSOS', 'active' => true],
            ['id' => 56, 'title' => 'DOR PÉLVICA', 'active' => true],
            ['id' => 57, 'title' => 'DOR RENAL', 'active' => true],
            ['id' => 58, 'title' => 'DOR TORÁCICA', 'active' => true],
            ['id' => 59, 'title' => 'ENJOO', 'active' => true],
            ['id' => 60, 'title' => 'ENVENENAMENTO', 'active' => true],
            ['id' => 61, 'title' => 'FAB - FERIMENTO POR ARMA BRANCA', 'active' => true],
            ['id' => 62, 'title' => 'FADIGA', 'active' => true],
            ['id' => 63, 'title' => 'FAF - FERIMENTO POR ARMA DE FOGO', 'active' => true],
            ['id' => 64, 'title' => 'FALTA DE AR', 'active' => true],
            ['id' => 65, 'title' => 'FEBRE', 'active' => true],
            ['id' => 66, 'title' => 'FERIDAS EM MEMBROS INFERIORES', 'active' => true],
            ['id' => 67, 'title' => 'FERIDAS EM MEMBROS SUPERIORES', 'active' => true],
            ['id' => 68, 'title' => 'FORMIGAMENTO NAS PERNAS', 'active' => true],
            ['id' => 69, 'title' => 'FRAQUEZA', 'active' => true],
            ['id' => 70, 'title' => 'FRATURA EM MEMBROS INFERIORES', 'active' => true],
            ['id' => 71, 'title' => 'FRATURA EM MEMBROS SUPERIORES', 'active' => true],
            ['id' => 72, 'title' => 'FRIO', 'active' => true],
            ['id' => 73, 'title' => 'GRIPE/RESFRIADO', 'active' => true],
            ['id' => 74, 'title' => 'INCHAÇO EM MEMBROS INFERIORES', 'active' => true],
            ['id' => 75, 'title' => 'INCHAÇO EM MEMBROS SUPERIORES', 'active' => true],
            ['id' => 76, 'title' => 'INTERNAÇAO', 'active' => true],
            ['id' => 77, 'title' => 'MAL ESTAR', 'active' => true],
            ['id' => 78, 'title' => 'MAMA ENDURECIDA', 'active' => true],
            ['id' => 79, 'title' => 'MANCHAS NA PELE', 'active' => true],
            ['id' => 80, 'title' => 'MASTITE (DOR NAS MAMAS)', 'active' => true],
            ['id' => 81, 'title' => 'MEDICAÇÃO', 'active' => true],
            ['id' => 82, 'title' => 'MORDEDURA DE COBRA', 'active' => true],
            ['id' => 83, 'title' => 'MORDEDURA DE GATO/CACHORRO', 'active' => true],
            ['id' => 84, 'title' => 'NÃO INFORMADO', 'active' => true],
            ['id' => 85, 'title' => 'OUTROS', 'active' => true],
            ['id' => 86, 'title' => 'PARADA CARDIACA', 'active' => true],
            ['id' => 87, 'title' => 'PARALISIA EM PARTE DO CORPO', 'active' => true],
            ['id' => 88, 'title' => 'PELE AMARELA (ICTERÍCIA)', 'active' => true],
            ['id' => 89, 'title' => 'PERDA DE LÍQUIDO VIA VAGINAL', 'active' => true],
            ['id' => 90, 'title' => 'PERFURAÇÃO POR OBJETO PONTIAGUDO', 'active' => true],
            ['id' => 91, 'title' => 'PICADA DE INSETO OUTROS', 'active' => true],
            ['id' => 92, 'title' => 'PICADA DE INSETO PEÇONHENTO', 'active' => true],
            ['id' => 93, 'title' => 'POLITRAUMA', 'active' => true],
            ['id' => 94, 'title' => 'PRESSÃO ALTA', 'active' => true],
            ['id' => 95, 'title' => 'PRESSÃO BAIXA', 'active' => true],
            ['id' => 96, 'title' => 'PRESSÃO NA PELVIS', 'active' => true],
            ['id' => 97, 'title' => 'PROBLEMAS RESPIRATÓRIOS', 'active' => true],
            ['id' => 98, 'title' => 'PROCEDIMENTO COM CIRURGIÃO', 'active' => true],
            ['id' => 99, 'title' => 'QUEDA', 'active' => true],
            ['id' => 100, 'title' => 'QUEDA DA PRÓPRIA ALTURA', 'active' => true],
            ['id' => 101, 'title' => 'QUEDA DE BICICLETA', 'active' => true],
            ['id' => 102, 'title' => 'QUEDA DE MOTO', 'active' => true],
            ['id' => 103, 'title' => 'QUEDA MAIOR QUE A PRÓPRIA ALTURA', 'active' => true],
            ['id' => 104, 'title' => 'QUEIMADURA', 'active' => true],
            ['id' => 105, 'title' => 'REAÇÃO ALÉRGICA', 'active' => true],
            ['id' => 106, 'title' => 'RECEITA DE REMEDIO CONTROLADO', 'active' => true],
            ['id' => 107, 'title' => 'RETORNO', 'active' => true],
            ['id' => 108, 'title' => 'RETORNO  COM ORTOPEDIA', 'active' => true],
            ['id' => 109, 'title' => 'RETORNO CLINICO', 'active' => true],
            ['id' => 110, 'title' => 'RETORNO COM BUCOMAXILO', 'active' => true],
            ['id' => 111, 'title' => 'RETORNO COM PEDIATRA', 'active' => true],
            ['id' => 112, 'title' => 'SANGRAMENTO NA BOCA', 'active' => true],
            ['id' => 113, 'title' => 'SANGRAMENTO NASAL', 'active' => true],
            ['id' => 114, 'title' => 'SANGRAMENTO NASAL', 'active' => true],
            ['id' => 115, 'title' => 'SANGRAMENTO NO OUVIDO', 'active' => true],
            ['id' => 116, 'title' => 'SANGRAMENTO VIA VAGINAL', 'active' => true],
            ['id' => 117, 'title' => 'TONTURA', 'active' => true],
            ['id' => 118, 'title' => 'TORÇÃO', 'active' => true],
            ['id' => 119, 'title' => 'TOSSE', 'active' => true],
            ['id' => 120, 'title' => 'TRABALHO DE PARTO', 'active' => true],
            ['id' => 121, 'title' => 'TRANSTORNOS PSIQUIATRICOS', 'active' => true],
            ['id' => 122, 'title' => 'TRAUMA', 'active' => true],
            ['id' => 123, 'title' => 'TRAUMA ABDOMINAL', 'active' => true],
            ['id' => 124, 'title' => 'TRAUMA EM BACIA/CINTURA PELVICA', 'active' => true],
            ['id' => 125, 'title' => 'TRAUMA EM REGIÃO TORÁCICA', 'active' => true],
            ['id' => 126, 'title' => 'VÔMITO', 'active' => true],
            ['id' => 127, 'title' => 'VÔMITO COM SANGUE', 'active' => true],
        ];

        DB::table('reasons')->insert($reasons);
    }
}
